@host = https://localhost:44335

### List Feed
GET {{host}}/api/Feeds
Content-Type: application/json

### Create Feed
POST {{host}}/api/Feeds
Content-Type: application/json

{
    "FeedTitle": "Knight Title",
    "FeedLike":"999",
    "FeedCreatedDateTime":"2018/11/24 12:34",
    "FeedCreatedUser":"Knight",
    "FeedValidFlag":true,
}

### Create Feed
POST {{host}}/api/Feeds
Content-Type: application/json

{
    "FeedTitle": "Knight Title",
}

### Update Like
POST {{host}}/api/Feeds/UpdateLike/4

### Get Like User List
GET {{host}}/api/feeds/GetLikeUserList/11

### Notify
Get {{host}}/api/Notify/Send/ValentinoRossi