@host = https://localhost:44335

### List
GET {{host}}/api/Feeds
Content-Type: application/json

### Create 
POST {{host}}/api/Feeds
Content-Type: application/json

{
    "FeedTitle": "Knight Title",
    "FeedLike":"999",
    "FeedCreatedDateTime":"2018/11/24 12:34",
    "FeedCreatedUser":"Knight",
    "FeedValidFlag":"1",
}

### Update Like
POST {{host}}/api/Feeds/UpdateLike/4

